Task logger
it-top-irkutsk/Messenger pull request #1
Opened 2021-05-31 11:56 UTC by LetRuin

2021-05-31 12:07 UTC, anst-foto commented
![](https://github.trello.services/images/mini-trello-icon.png) [#task_logger Доработать систему журналирования](https://trello.com/c/9jKqN8my/13-tasklogger-%D0%B4%D0%BE%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D1%82%D1%8C-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%83-%D0%B6%D1%83%D1%80%D0%BD%D0%B0%D0%BB%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)

2021-05-31 12:09 UTC, romzes2006 requested changes

2021-05-31 12:09 UTC, romzes2006 commented on Logger/Logger.cs
> +                Console.WriteLine("e");
А если у нас будет приложение WPF? То доступа к консоли не будет...

2021-05-31 12:09 UTC, romzes2006 commented on Logger/Logger.cs
> +                    Console.WriteLine("e");
А если у нас будет приложение WPF? То доступа к консоли не будет...

2021-05-31 12:20 UTC, anst-foto requested changes
Дорабатывать!

2021-05-31 12:20 UTC, anst-foto commented on Logger/Logger.cs
> +        private SqliteConnection bd;
```suggestion
        private SqliteConnection _db;
```
Правильно по англ. БД пишется DB

2021-05-31 12:20 UTC, anst-foto commented on Logger/Logger.cs
> +                    command.CommandText = "message";
Будем `"message"` передавать вместо строки `SQL`???

2021-05-31 12:20 UTC, anst-foto commented on Logger/README.md
> +LogType.Error (тип Ошибка)
```suggestion
- LogType.Info - Информационный
- LogType.Success - Успешный
- LogType.Warning - Предупреждение
- LogType.Error - Ошибка
```

2021-05-31 12:20 UTC, anst-foto commented on Logger/README.md
> +Error (Принимает String Сообщение) (Записывает Ошибку в SQLite)
Более подробное описание что принимает, что записывает. Посмотри как другие API написаны.

2021-06-01 10:46 UTC, Shtreehcode-Tona commented on Logger/Logger.cs
> +                Console.WriteLine("e");
> А если у нас будет приложение WPF? То доступа к консоли не будет...

Можно делать без отсылки в консоль, пусть будет окошко с ошибкой, его будут отправлять техадмину,

2021-06-01 10:46 UTC, Shtreehcode-Tona commented on Logger/Logger.cs
> +                bd = new SqliteConnection("nameBD");
_db = new SqliteConnection("nameDB");

2021-06-01 10:52 UTC, Shtreehcode-Tona commented on Logger/Logger.cs
> +        private const string nameBD = "Data Source=Log.sqlite";
private const string nameDB = "Data Source=Log.sqlite";

2021-06-01 10:52 UTC, Shtreehcode-Tona commented on Logger/Logger.cs
> +                _db = new SqliteConnection("nameBD");
_db = new SqliteConnection("nameDB");

2021-06-01 10:52 UTC, Shtreehcode-Tona commented on Logger/Logger.cs
> +                throw new Exception($"{e}");
В будущем можем забыть что значит это 'e', лучше обозвать более информативно

2021-06-01 11:24 UTC, LetRuin commented on Logger/Logger.cs
> +                throw new Exception($"{e}");
'е' это временная переменная которая содержит в себе данные ошибки написанные в тех командах которые используем, я изменил на свой текст описание ошибок.

2021-06-01 11:25 UTC, LetRuin commented on Logger/Logger.cs
> +                _db = new SqliteConnection("nameBD");
изменил BD на DB.

2021-06-01 11:25 UTC, LetRuin commented on Logger/Logger.cs
> +        private const string nameBD = "Data Source=Log.sqlite";
изменил BD на DB

2021-06-01 12:25 UTC, LetRuin commented on Logger/Logger.cs
> +                Console.WriteLine("e");
Написал окошко с выводом ошибки пользователю.

2021-06-01 12:27 UTC, LetRuin commented on Logger/Logger.cs
> +                    command.CommandText = "message";
Изменил теперь отправляет в консоль запрос SQL

2021-06-01 12:43 UTC, anst-foto requested changes
Избавиться от явных реализаций интерфейса по взаимодействию с пользователем

2021-06-01 12:43 UTC, anst-foto commented on Logger/Logger.cs
> +                MessageBox.Show(exception, "Ошибка", MessageBoxButton.OK, MessageBoxImage.Error);
Откуда тут взялся `MessageBox`? Если нужно вывести сообщение, то нужно использовать либо `event`, либо `throw`

2021-06-01 12:43 UTC, anst-foto commented on Logger/Logger.cs
> +                    MessageBox.Show(exception, "Ошибка", MessageBoxButton.OK, MessageBoxImage.Error);
Откуда тут взялся `MessageBox`? Если нужно вывести сообщение, то нужно использовать либо `event`, либо `throw`

2021-06-01 12:50 UTC, LetRuin commented on Logger/Logger.cs
> +                    MessageBox.Show(exception, "Ошибка", MessageBoxButton.OK, MessageBoxImage.Error);
убрал messagebox

2021-06-01 12:50 UTC, LetRuin commented on Logger/Logger.cs
> +                MessageBox.Show(exception, "Ошибка", MessageBoxButton.OK, MessageBoxImage.Error);
убрал messagebox

2021-06-01 12:56 UTC, anst-foto reviewed
А не проще было бы добавить `event`

2021-06-03 11:06 UTC, romzes2006 commented on Logger/Logger.cs
> +                    MessageBox.Show(exception, "Ошибка", MessageBoxButton.OK, MessageBoxImage.Error);
Согласен. Думаю использование исключений приоритетнее.

2021-06-03 11:08 UTC, romzes2006 approved these changes

2021-06-07 10:32 UTC, anst-foto approved these changes
Принимаю.

2021-06-07 10:34 UTC, merged