Добавление классов сообщений
it-top-irkutsk/Messenger pull request #2
Opened 2021-06-01 11:57 UTC by Rasmus3

2021-06-01 12:01 UTC, anst-foto commented
![](https://github.trello.services/images/mini-trello-icon.png) [#task_message Создать структуру отправки сообщения (сервер-клиент)](https://trello.com/c/NAylPZpn/23-taskmessage-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C-%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D1%83-%D0%BE%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B8-%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D1%8F-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82)

2021-06-01 12:18 UTC, LetRuin commented on Message_Types/Class1.cs
> +    }
ConDiscon название класса непонятное и choice что означает какой выбор?
может имел ввиду название класса Connect а bool как connected

2021-06-01 12:23 UTC, anst-foto requested changes
Не понял структуру классов, зачем перечисление и наследники.
Не понятны сокращения названий.

2021-06-01 12:23 UTC, anst-foto commented on Message_Types/Class1.cs
> +    }
Где используется сиё перечисление?

2021-06-01 12:23 UTC, anst-foto commented on Message_Types/Class1.cs
> +    }
Что это за класс? Зачем нужен класс, когда есть перечисления?

2021-06-01 12:23 UTC, anst-foto commented on Message_Types/Class1.cs
> +    }
Для чего наследование?

2021-06-01 12:23 UTC, romzes2006 requested changes

2021-06-01 12:23 UTC, romzes2006 commented on Message_Types/Class1.cs
> +    }
Вводит в заблуждение. Необходимо дать понятные наименования.

2021-06-01 12:23 UTC, romzes2006 commented on Message_Types/Class1.cs
> +    }
Не совсем понял, зачем этот класс нужен.

2021-06-01 12:35 UTC, LetRuin requested changes

2021-06-01 12:35 UTC, LetRuin commented on Message_Types/Message_types.cs
> +        public Enum Type;
надо так public TypesMsg Type;

2021-06-01 12:37 UTC, anst-foto requested changes
Нет поля для самого текста сообщения

2021-06-01 12:37 UTC, anst-foto commented on Message_Types/Message_types.cs
> +        public string Name;
Что за имя? Имя получателя или отправителя?

2021-06-01 12:37 UTC, anst-foto commented on Message_Types/Message_types.cs
> +        public Enum Type;
```suggestion
        public TypesMsg Type;
```

2021-06-01 12:37 UTC, anst-foto commented on Message_Types/Message_types.cs
> +        public string Chat;
Это id чата или его название?

2021-06-01 12:54 UTC, LetRuin requested changes

2021-06-01 12:54 UTC, LetRuin commented on Message_Types/Message_types.cs
> +        public string NameChat;
Отсутствует строка сообщения.

2021-06-01 12:58 UTC, anst-foto requested changes
Внимательно смотри что написали в ревью кода.

2021-06-01 12:58 UTC, anst-foto commented on Message_Types/Message_types.cs
> +        public string NameChat;
Согласен

2021-06-01 13:01 UTC, anst-foto reviewed
Класс принимается. Но где описание и примеры?

2021-06-03 11:03 UTC, romzes2006 approved these changes

2021-06-03 11:32 UTC, LetRuin approved these changes

2021-06-08 11:42 UTC, merged

2021-06-14 12:21 UTC, anst-foto reviewed
Немного переделать

2021-06-14 12:21 UTC, anst-foto commented on Message_Types/Message_types.cs
> +    }
Вынеси в отдельный файл

2021-06-14 12:21 UTC, anst-foto commented on Message_Types/Message_types.cs
> +
Лишняя пустая строка