Task startup
it-top-irkutsk/Messenger pull request #4
Opened 2021-06-08 06:31 UTC by romzes2006

Разработан дизайн окна авторизации

2021-06-08 10:24 UTC, romzes2006 commented
![](https://github.trello.services/images/mini-trello-icon.png) [#task_startup Разработать приложение для старта](https://trello.com/c/PkgK6LPZ/19-taskstartup-%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D1%82%D1%8C-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B4%D0%BB%D1%8F-%D1%81%D1%82%D0%B0%D1%80%D1%82%D0%B0)

2021-06-08 11:36 UTC, anst-foto requested changes
Смотрите комментарии

2021-06-08 11:36 UTC, anst-foto commented on Messenger/MainWindow.xaml
> +                            </Border.Style>
Можно поместить в `<Window.Resources>`

2021-06-08 11:36 UTC, anst-foto commented on Messenger/MainWindow.xaml
> +
Пустые строки лучше удалить

2021-06-08 11:36 UTC, anst-foto commented on Messenger/MainWindow.xaml.cs
> +            }
Что здесь должно обрабатываться?

2021-06-08 11:36 UTC, anst-foto commented on StartUp/readme.md
> +## ����� ������ (�������� �������. ���������� �������� �� ����������� ���������):
Кодировка!

2021-06-08 11:36 UTC, anst-foto commented on StartUp/readme.md
> +```
```suggestion
```xml
<Border HorizontalAlignment="Center" CornerRadius="10" BorderThickness="1" Background="Black" .....>
<Button Style="{StaticResource Super_button}" FontSize="22" ....." />
```
```

2021-06-08 11:36 UTC, anst-foto commented on StartUp/readme.md
> +```sh
```suggestion
```xml
```

2021-06-08 11:43 UTC, romzes2006 commented on Messenger/MainWindow.xaml
> +                            </Border.Style>
Прошу научить, как?

2021-06-08 11:49 UTC, romzes2006 commented on Messenger/MainWindow.xaml.cs
> +            }
При получении фокуса ввода, надпись "Логин" удаляется. Решение "кривое", есть более элегантное на XAML

2021-06-08 11:49 UTC, romzes2006 commented on StartUp/readme.md
> +## ����� ������ (�������� �������. ���������� �������� �� ����������� ���������):
Исправлено
В коммите UTF-8

2021-06-08 11:51 UTC, anst-foto requested changes
Кодировку поменяли, но ещё не применили предложенные изменения

2021-06-08 12:06 UTC, anst-foto requested changes
Доработать `README.md`

2021-06-08 12:06 UTC, anst-foto commented on StartUp/readme.md
> +```sh
```suggestion
```xml
```

2021-06-08 12:06 UTC, anst-foto commented on StartUp/readme.md
> +<Button Style="{StaticResource Super_button}" FontSize="22" ....." />
Нет закрывающего ` ``` `

2021-06-08 12:06 UTC, anst-foto commented on StartUp/readme.md
> +Цвет кнопок - #272537
Зачем текст , а точнее список помещать в многострочный код?

2021-06-29 11:26 UTC, anst-foto approved these changes
OK

2021-06-29 11:27 UTC, merged