Task msg types
it-top-irkutsk/Messenger pull request #6
Opened 2021-06-10 10:53 UTC by Rasmus3

Добавление класса авторизации 
Изменение типов

2021-06-10 11:37 UTC, LetRuin approved these changes
Одобряю

2021-06-10 11:42 UTC, anst-foto requested changes
Доработать.
Внести изменения в документацию.

2021-06-10 11:42 UTC, anst-foto commented on Message_Types/Authorization.cs
> +        bool Validation { get; set; }
Точно нужно это свойство?

2021-06-10 11:42 UTC, anst-foto commented on Message_Types/Msg.cs
> +        public DateTime Date { get; set; }
Они изначально нужны были

2021-06-10 11:42 UTC, anst-foto commented on Message_Types/Msg.cs
> +
Лишняя пустая строка

2021-06-21 11:28 UTC, LetRuin approved these changes

2021-06-21 11:29 UTC, anst-foto approved these changes
Принимается

2021-06-21 11:30 UTC, merged